spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    driverClassName:
  Jpa:
    hibernate:
      ddl-auto: none
        show-sql: false
