global:
  message: welcome to order service production environment
server:
  port: 8085
    message: This is hello from order prod !
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: 
    Jpa:
    hibernate:
      ddl-auto: update
        show-sql: true
   
